defaultEntryPoints = ["http", "https"]
#insecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[acme]
  email = "apkd@users.noreply.github.com"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  entryPoint = "https"
  onHostRule = true	

  [acme.tlsChallenge]
